name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4.1.3
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: '0.125.3'
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.11'
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2.2.0
      with:
        version: '0.12.0'
    - name: Setup Go
      uses: actions/setup-go@v5.0.0
    - name: Install Pico SDK dependencies
      run: |
        sudo apt update
        sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential gcc
        python3 -m pip install numpy matplotlib tqdm icecream
    - name: Checkout pico-sdk
      uses: actions/checkout@v4.1.3
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        submodules: true
    - name: Set PICO_SDK_PATH
      run: echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV
    - name: Build zeptocore
      run:
        make zeptocore
    - name: Build ectocore
      run:
        make ectocore
    - name: Build core_windows.exe
      run:
        make core_windows.exe