name: Build UF2 File on Release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
    - name: Setup Go
      uses: actions/setup-go@v4
    - name: Install Pico SDK dependencies
      run: |
        sudo apt update
        sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential gcc wget tar
        python3 -m pip install numpy matplotlib tqdm icecream
    - name: Checkout pico-sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        submodules: true
    - name: Set PICO_SDK_PATH
      run: echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV
    - name: Build UF2s
      run: |
        make zeptocore
        make ectocore
        make core_windows.exe
        make core_linux_amd64
        make core_macos_aarch64
        make core_macos_amd64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          zeptocore.uf2
          ectocore.uf2
          core_windows.exe
          core_linux_amd64
          core_macos_amd64
          core_macos_aarch64